import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2 {
            font-size: 38px;
          }
          h3 {
            font-size: 28 px;
          }
        `}
      </style>

      <Head>
        <title>Hounting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hunting Coder</h1>

        <div className={styles.imgWrap}>
          <Image
            src="/homeimg.jpg"
            alt="homeimg"
            width={640}
            height={427}
            className={styles.myImg}
          />
        </div>

        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>

        <div>
          <h2>Popular Blogs</h2>
          <div>
            <h3>How to learn JS in 2022?</h3>
            <p>
              Js is the language for hdghft ghfgty gfbghuk jgghcftre uiyjgmhs
              erfhg ytrghhmgyu...............
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
